#include <stdio.h>

void printConversionOptions(void);

int takeConversionType(int conversionType);

//Length Conversions
void printLengthOptions(void);
int lengthConversion(int from, int to);
//From Kilometer
void convertKilometerToKilometer(void);
void convertKilometerToMeter(void);
void convertKilometerToCentimeter(void);
void convertKilometerToMillimeter(void);
void convertKilometerToMicrometer(void);
void convertKilometerToNanometer(void);
void convertKilometerToMile(void);
void convertKilometerToYard(void);
void convertKilometerToFoot(void);
void convertKilometerToInch(void);
void convertKilometerToNauticalMile(void);
//From Meter
void convertMeterToKilometer(void);
void convertMeterToMeter(void);
void convertMeterToCentimeter(void);
void convertMeterToMillimeter(void);
void convertMeterToMicrometer(void);
void convertMeterToNanometer(void);
void convertMeterToMile(void);
void convertMeterToYard(void);
void convertMeterToFoot(void);
void convertMeterToInch(void);
void convertMeterToNauticalMile(void);
//From Centimeter
void convertCentimeterToKilometer(void);
void convertCentimeterToMeter(void);
void convertCentimeterToCentimeter(void);
void convertCentimeterToMillimeter(void);
void convertCentimeterToMicrometer(void);
void convertCentimeterToNanometer(void);
void convertCentimeterToMile(void);
void convertCentimeterToYard(void);
void convertCentimeterToFoot(void);
void convertCentimeterToInch(void);
void convertCentimeterToNauticalMile(void);
//From Millimeter
void convertMillimeterToKilometer(void);
void convertMillimeterToMeter(void);
void convertMillimeterToCentimeter(void);
void convertMillimeterToMillimeter(void);
void convertMillimeterToMicrometer(void);
void convertMillimeterToNanometer(void);
void convertMillimeterToMile(void);
void convertMillimeterToYard(void);
void convertMillimeterToFoot(void);
void convertMillimeterToInch(void);
void convertMillimeterToNauticalMile(void);
//From Micrometer
void convertMicrometerToKilometer(void);
void convertMicrometerToMeter(void);
void convertMicrometerToCentimeter(void);
void convertMicrometerToMillimeter(void);
void convertMicrometerToMicrometer(void);
void convertMicrometerToNanometer(void);
void convertMicrometerToMile(void);
void convertMicrometerToYard(void);
void convertMicrometerToFoot(void);
void convertMicrometerToInch(void);
void convertMicrometerToNauticalMile(void);
//From Nanometer
void convertNanometerToKilometer(void);
void convertNanometerToMeter(void);
void convertNanometerToCentimeter(void);
void convertNanometerToMillimeter(void);
void convertNanometerToMicrometer(void);
void convertNanometerToNanometer(void);
void convertNanometerToMile(void);
void convertNanometerToYard(void);
void convertNanometerToFoot(void);
void convertNanometerToInch(void);
void convertNanometerToNauticalMile(void);
//From Mile
void convertMileToKilometer(void);
void convertMileToMeter(void);
void convertMileToCentimeter(void);
void convertMileToMillimeter(void);
void convertMileToMicrometer(void);
void convertMileToNanometer(void);
void convertMileToMile(void);
void convertMileToYard(void);
void convertMileToFoot(void);
void convertMileToInch(void);
void convertMileToNauticalMile(void);
//From Yard
void convertYardToKilometer(void);
void convertYardToMeter(void);
void convertYardToCentimeter(void);
void convertYardToMillimeter(void);
void convertYardToMicrometer(void);
void convertYardToNanometer(void);
void convertYardToMile(void);
void convertYardToYard(void);
void convertYardToFoot(void);
void convertYardToInch(void);
void convertYardToNauticalMile(void);
//From Foot
void convertFootToKilometer(void);
void convertFootToMeter(void);
void convertFootToCentimeter(void);
void convertFootToMillimeter(void);
void convertFootToMicrometer(void);
void convertFootToNanometer(void);
void convertFootToMile(void);
void convertFootToYard(void);
void convertFootToFoot(void);
void convertFootToInch(void);
void convertFootToNauticalMile(void);
//From Inch
void convertInchToKilometer(void);
void convertInchToMeter(void);
void convertInchToCentimeter(void);
void convertInchToMillimeter(void);
void convertInchToMicrometer(void);
void convertInchToNanometer(void);
void convertInchToMile(void);
void convertInchToYard(void);
void convertInchToFoot(void);
void convertInchToInch(void);
void convertInchToNauticalMile(void);
//From Nautical Mile
void convertNauticalMileToKilometer(void);
void convertNauticalMileToMeter(void);
void convertNauticalMileToCentimeter(void);
void convertNauticalMileToMillimeter(void);
void convertNauticalMileToMicrometer(void);
void convertNauticalMileToNanometer(void);
void convertNauticalMileToMile(void);
void convertNauticalMileToYard(void);
void convertNauticalMileToFoot(void);
void convertNauticalMileToInch(void);
void convertNauticalMileToNauticalMile(void);